---
# TEST.0001
# This is just a basic example


- hosts: all
  name: TEST.0001
  vars_files:
    - vars.yml

  tasks:

    - name: Standardized initial state
      import_tasks: includes/clean_initial_state.yml

    - name: Perform simple connectivity test
      ping:

    - yum:
        name: bind-utils
        state: latest

    - command: host "{{ ansible_fqdn }}"
      register: forward_host_out

    - command: host "{{ ansible_all.ipv4_addresses[0] }}"
      register: reverse_host_out

    - name: Check we are correctly registered in forward DNS
      debug:
        var: forward_host_out
        