---
# TEST.0001
# This is just a basic example


- hosts: all
  name: TEST.0001
  vars_files:
    - vars.yml

  tasks:

    - name: Standardized initial state
      import_tasks: includes/clean_initial_state.yml

    - name: Perform simple connectivity test
      ping:

    - yum:
        name: bind-utils
        state: latest

    - shell: host "{{ ansible_fqdn }}" | awk '{print $NF}'
      register: forward_host_out

    - shell: host "{{ ansible_all_ipv4_addresses[0] }}" | awk '{print $NF}' | sed s/.$//
      register: reverse_host_out

    - name: Check we are correctly registered in forward DNS
      debug:
        var: forward_host_out

    - name: Check we are correctly registered in reverse DNS
      debug:
        var: reverse_host_out